import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';

export interface JobPdfData {
  title: string;
  department?: string;
  location?: string;
  experience_required?: string;
  description: string;
  required_skills?: string;
}

@Injectable()
export class PdfGeneratorService {
  private readonly logger = new Logger(PdfGeneratorService.name);

  /**
   * Generates a professionally styled PDF document of the Job Description in memory.
   * @param job Job specification details
   * @returns Promise<Buffer> of the generated PDF
   */
  async generateJobDescriptionPdf(job: JobPdfData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50,
          info: {
            Title: `Job Description - ${job.title}`,
            Author: 'RecruitFlow Talent Platform',
            Subject: 'Technical Interview Job Specification',
          },
        });

        const chunks: Buffer[] = [];
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => {
          const pdfBuffer = Buffer.concat(chunks);
          this.logger.log(
            `[PdfGenerator] Generated JD PDF for "${job.title}" (${pdfBuffer.length} bytes)`,
          );
          resolve(pdfBuffer);
        });
        doc.on('error', (err) => {
          this.logger.error(
            `[PdfGenerator] Error generating JD PDF: ${err.message}`,
          );
          reject(err);
        });

        // Header: Brand & Title
        doc
          .fontSize(22)
          .font('Helvetica-Bold')
          .fillColor('#09090b')
          .text('RecruitFlow', { align: 'left' });

        doc
          .fontSize(9)
          .font('Helvetica')
          .fillColor('#71717a')
          .text('Candidate Screening & Technical Evaluation Platform', {
            align: 'left',
          });

        doc.moveDown(0.8);

        // Job Title
        doc
          .fontSize(16)
          .font('Helvetica-Bold')
          .fillColor('#18181b')
          .text(job.title);

        doc.moveDown(0.3);

        // Meta Info (Department | Location | Experience)
        const metaItems = [
          job.department ? `Department: ${job.department}` : null,
          job.location ? `Location: ${job.location}` : null,
          job.experience_required
            ? `Experience: ${job.experience_required}`
            : null,
        ]
          .filter(Boolean)
          .join('   |   ');

        if (metaItems) {
          doc
            .fontSize(10)
            .font('Helvetica')
            .fillColor('#52525b')
            .text(metaItems);
        }

        doc.moveDown(0.8);

        // Horizontal Divider Rule
        doc
          .strokeColor('#e4e4e7')
          .lineWidth(1)
          .moveTo(50, doc.y)
          .lineTo(545, doc.y)
          .stroke();

        doc.moveDown(1);

        // Section: Required Technical Skills & Competencies
        if (job.required_skills && job.required_skills.trim().length > 0) {
          doc
            .fontSize(12)
            .font('Helvetica-Bold')
            .fillColor('#09090b')
            .text('Required Technical Skills & Competencies');

          doc.moveDown(0.4);

          // Render skills as formatted bullets or comma-separated tags
          const skillsList = job.required_skills
            .split(/[,;\n]/)
            .map((s) => s.trim())
            .filter((s) => s.length > 0);

          if (skillsList.length > 0) {
            for (const skill of skillsList) {
              doc
                .fontSize(10)
                .font('Helvetica')
                .fillColor('#27272a')
                .text(`•  ${skill}`, { indent: 10 });
            }
          } else {
            doc
              .fontSize(10)
              .font('Helvetica')
              .fillColor('#27272a')
              .text(job.required_skills);
          }

          doc.moveDown(1);
        }

        // Section: Job Description & Responsibilities
        doc
          .fontSize(12)
          .font('Helvetica-Bold')
          .fillColor('#09090b')
          .text('Job Description & Responsibilities');

        doc.moveDown(0.4);

        doc
          .fontSize(10)
          .font('Helvetica')
          .fillColor('#3f3f46')
          .text(job.description || 'No detailed description provided.', {
            align: 'justify',
            lineGap: 3,
          });

        doc.moveDown(1.5);

        // Footer
        doc
          .fontSize(8)
          .font('Helvetica')
          .fillColor('#a1a1aa')
          .text(
            `Generated by RecruitFlow Platform on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} • Confidential - For Interview Evaluation Only`,
            50,
            780,
            { align: 'center', width: 495 },
          );

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
